CC=cl
OUTDIR=build
OBJDIR=obj
TARGET=$(OUTDIR)\ecsvm.exe
!IFNDEF ECSVM_ENABLE_SDL3
ECSVM_ENABLE_SDL3=1
!ENDIF
SDL3_INCDIR=dependencies\include
SDL3_LIBDIR=dependencies\lib\x64
SDL3_DLL=dependencies\lib\x64\SDL3.dll

OBJFILES=$(OBJDIR)\component.obj \
	$(OBJDIR)\ecsbin.obj \
	$(OBJDIR)\ecsvm.obj \
	$(OBJDIR)\main.obj \
	$(OBJDIR)\project.obj \
	$(OBJDIR)\pong.obj

LEGACYOBJS=component.obj \
	ecsbin.obj \
	ecsvm.obj \
	main.obj \
	project.obj \
	pong.obj

!IF "$(ECSVM_ENABLE_SDL3)" == "1"
SDL3_CFLAGS=/I$(SDL3_INCDIR)
SDL3_LDFLAGS=/LIBPATH:$(SDL3_LIBDIR) SDL3.lib
SDL3_OBJFILES=$(OBJDIR)\system_renderer.obj \
	$(OBJDIR)\system_window.obj
LEGACYOBJS=$(LEGACYOBJS) \
	system_renderer.obj \
	system_window.obj
all: purgelegacyobjs $(TARGET) copydll
!ELSE
SDL3_CFLAGS=
SDL3_LDFLAGS=
SDL3_OBJFILES=
all: purgelegacyobjs $(TARGET)
!ENDIF

OBJFILES=$(OBJFILES) \
	$(SDL3_OBJFILES)

CFLAGS=/nologo /TC /std:c11 /W4 /WX /Iinclude $(SDL3_CFLAGS) /D_CRT_SECURE_NO_WARNINGS /DECSVM_ENABLE_SDL3=$(ECSVM_ENABLE_SDL3)
LDFLAGS=/link /NOLOGO /OUT:$(TARGET) $(SDL3_LDFLAGS)

purgelegacyobjs:
	@if exist component.obj del /Q component.obj
	@if exist ecsbin.obj del /Q ecsbin.obj
	@if exist ecsvm.obj del /Q ecsvm.obj
	@if exist main.obj del /Q main.obj
	@if exist project.obj del /Q project.obj
	@if exist pong.obj del /Q pong.obj
!IF "$(ECSVM_ENABLE_SDL3)" == "1"
	@if exist system_renderer.obj del /Q system_renderer.obj
	@if exist system_window.obj del /Q system_window.obj
!ENDIF

$(TARGET): $(OBJFILES)
	@if not exist $(OUTDIR) mkdir $(OUTDIR)
	$(CC) $(OBJFILES) $(LDFLAGS)

$(OBJDIR)\component.obj: src\component.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

$(OBJDIR)\ecsbin.obj: src\ecsbin.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

$(OBJDIR)\ecsvm.obj: src\ecsvm.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

$(OBJDIR)\main.obj: src\main.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

$(OBJDIR)\project.obj: src\project.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

$(OBJDIR)\pong.obj: src\pong.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

!IF "$(ECSVM_ENABLE_SDL3)" == "1"
$(OBJDIR)\system_renderer.obj: src\system_renderer.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**

$(OBJDIR)\system_window.obj: src\system_window.c
	@if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $**
!ENDIF

!IF "$(ECSVM_ENABLE_SDL3)" == "1"
copydll: $(TARGET)
	@copy /Y $(SDL3_DLL) $(OUTDIR)\SDL3.dll >NUL
!ENDIF

clean:
	@if exist $(OUTDIR)\ecsvm.exe del /Q $(OUTDIR)\ecsvm.exe
	@if exist $(OUTDIR)\SDL3.dll del /Q $(OUTDIR)\SDL3.dll
	@if exist $(OBJDIR) rmdir /S /Q $(OBJDIR)
	@if exist component.obj del /Q component.obj
	@if exist ecsbin.obj del /Q ecsbin.obj
	@if exist ecsvm.obj del /Q ecsvm.obj
	@if exist main.obj del /Q main.obj
	@if exist project.obj del /Q project.obj
	@if exist pong.obj del /Q pong.obj
	@if exist system_renderer.obj del /Q system_renderer.obj
	@if exist system_window.obj del /Q system_window.obj
